### ISSUE TITLE
Can't download Spotify playlist 

### ISSUE THREAD

**Issue by TheDoctor200** [sylviiu/ezytdl#134]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (C:\Users\m_web\AppData\Local\Programs\ezytdl\resources\app.asar\util\platforms\spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\m_web\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\m_web\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\m_web\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by TheDoctor200** [comment]
fixed the issue by creating a embedded url

**Comment by TheDoctor200** [comment]
unable to download metadat, thumbnail, and author so. 
Downloaded files cannot be converted to mp3 (downloaded files are in a m4a format)

**Comment by sylviiu** [comment]
This issue has been fixed in nightly / dev builds! Try turning that on in settings, and manually performing an update check in the tray menu!

**Comment by TheDoctor200** [comment]
Still doesn't work, it's stuck on parsing entry![image](https://github.com/sylviiu/ezytdl/assets/88980346/01b4db4b-6f72-4a56-ace6-dcc58a74900d)

**Comment by sylviiu** [comment]
i'm so sorry for taking so long on getting a reply back for this issue, lost motivation for most work i was doing for a minute lol

i've seen that issue pop up a few times on my side while implementing a new feature; a new nightly build should be built tomorrow! if you're still willing to test it, please let me know! :D

**Comment by TheDoctor200** [comment]
Of course and no problem, take your time :)) I will switch to the new nightly build now and test

**Comment by TheDoctor200** [comment]
![image](https://github.com/sylviiu/ezytdl/assets/88980346/5e271985-b751-4760-b29b-82a0aecdabd6)
![image](https://github.com/sylviiu/ezytdl/assets/88980346/5cbab2fe-fe28-4a94-be78-c7e78a42a203)

Tried both embedded and normal Spotify playlist now, but it's still stuck on something I think

**Comment by TheDoctor200** [comment]
In the newest devbuild, Playlist is loading up and everything seems to be fine, but I got multiple errors ![image](https://github.com/sylviiu/ezytdl/assets/88980346/30f9a9ec-69d0-4c57-b724-c544386f4cd7)afterwards
