### ISSUE TITLE
Extraneous ASCII characters, stunted off-platform downloads.

### ISSUE THREAD

**Issue by avatarDD** [sylviiu/ezytdl#49]
Try to download https://open.spotify.com/album/22UN42206haF1yk97rVPIR

### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (C:\Users\user\AppData\Local\Programs\ezytdl\resources\app.asar\util\platforms\spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\user\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\user\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\user\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
This issue has previously been patched in nightly / dev builds. [Try installing the latest dev build](https://github.com/sylviiu/ezytdl/releases/tag/3.0.0-dev.147) and try downloading again.

**Comment by avatarDD** [comment]
Ok. It's work.

Another problem: why when i download by yt-dlp not setting titles of track?

**Comment by avatarDD** [comment]
Also when try to download full album first 3 tracks is freezing

**Comment by sylviiu** [comment]
Glad it's working.

> Another problem: why when i downloading album by yt-dlp it's not setting titles of track?

Are you talking about the metadata? If so, do you have FFmpeg installed? That's needed to embed metadata.

**Comment by sylviiu** [comment]
> Also when try to download full album first 3 tracks is freezing

When it freezes, does it say anything? Does it give you any errors during download?

**Comment by avatarDD** [comment]
> Glad it's working.
> 
> > Another problem: why when i downloading album by yt-dlp it's not setting titles of track?
> 
> Are you talking about the metadata? If so, do you have FFmpeg installed? That's needed to embed metadata.

I mean ArtistName and SongName in the name of file + TAGs.
Also extraneous ascii characters are put in album folder names, which shouldn't be there.
Yes FFmpeg installed.
![изображение](https://github.com/sylviiu/ezytdl/assets/11490349/2d74333f-4478-42a5-8761-f4011d397823)
![изображение](https://github.com/sylviiu/ezytdl/assets/11490349/e13be79e-6c41-4332-9ffc-6e7e45910369)
![изображение](https://github.com/sylviiu/ezytdl/assets/11490349/660e5ac6-24b3-4e91-b8cb-49dc1f5e28ec)
![изображение](https://github.com/sylviiu/ezytdl/assets/11490349/bf85db3a-f9d9-41a5-91f5-39683fe40167)

**Comment by avatarDD** [comment]
> 
> > Also when try to download full album first 3 tracks is freezing
> 
> When it freezes, does it say anything? Does it give you any errors during download?

No. It doesn't say anything.

> > Also when try to download full album first 3 tracks is freezing
> 
> When it freezes, does it say anything? Does it give you any errors during download?

No, it doesn't say anything.
There are always 3 downloads freeze. Usually, these are the first three tracks from the album. And if I try to re-download them again (not the entire album, but the concret tracks) they are successfully will be downloaded.
![изображение](https://github.com/sylviiu/ezytdl/assets/11490349/6c413344-99b9-4064-9f06-1d201481bd5d)

**Comment by sylviiu** [comment]
Ah, yeah. The extraneous ASCII characters have been a bug with the python bridge I wrote (issues with string encoding) which I still have yet to figure out why it happens. I'll look into that.

For a temporary workaround, when downloading the files, try renaming the destination folder in this text box.
![image](https://github.com/sylviiu/ezytdl/assets/95180094/57802ad8-a188-44f2-9e42-eac53de7b3cd)

~~Insult to injury, 7 downloads from the playlist were broken for me.~~
![image](https://github.com/sylviiu/ezytdl/assets/95180094/ddde8756-7f64-4b37-a17b-71a622d7e274)

I'll look into all of it right now.

**Comment by sylviiu** [comment]
I was able to replicate the issue of downloading to the incorrect folder.
![image](https://github.com/sylviiu/ezytdl/assets/95180094/03bc5e62-a95e-4cf6-a14e-0cf5dbc11e98)

Good news is, I fixed the issue of downloading to the incorrect folder -- I had to force the bridge to read stdin as UTF-8 (I think it was defaulting to ASCII); hopefully this will be fixed by the next nightly build in a couple hours!
![image](https://github.com/sylviiu/ezytdl/assets/95180094/927b177a-eebb-4baa-9d44-bff0298d80bb)

**Comment by avatarDD** [comment]
Good 👍

**Comment by avatarDD** [comment]
Can you also add creating folder with artistName before creating folder with albumName?
I mean:
diskName:\siteName\artistName\albumName\filename.ext

thanks a lot

**Comment by sylviiu** [comment]
> Can you also add creating folder with artistName before creating folder with albumName?

That's also something I've been wanting but never got around to. Will add!

**Comment by sylviiu** [comment]
All download path issues have been fixed. Everything relating to the pybridge have been built and released (build 68), you can update it in-app now.

![image](https://github.com/sylviiu/ezytdl/assets/95180094/b6e7c6b9-fdec-41bc-94ab-fab8d71ea782)
![image](https://github.com/sylviiu/ezytdl/assets/95180094/d67c767c-19e7-478e-bda4-b04411c08228)

I did however come across another bug where the songs (not sure if it's this album in particular or any on Spotify, we'll go with the latter) saved as `[ Unknown ] Unknown - Unknown` (as shown in above picture), which has been fixed. You can try downloading these again, but if they don't work, the next nightly release should build in a little over an hour from now.

*I also think this might have fixed the issue where the other 3 downloads wouldn't start, but if that continues let me know, I'll try to figure out another patch for it.*

I'm going to close this as completed for now, but if the issue persists please feel free to reopen. I'll still add the `diskName:\siteName\artistName\albumName\filename.ext` feature.

**Comment by sylviiu** [comment]
> Can you also add creating folder with artistName before creating folder with albumName?

Done!
![image](https://github.com/sylviiu/ezytdl/assets/95180094/08df9e40-191a-4c3c-87d6-c140365f4528)

This will be available in the next nightly release as well. :D

**Comment by avatarDD** [comment]
The problem with 3 freezing loading still exists.
![изображение](https://github.com/sylviiu/ezytdl/assets/11490349/4e08751a-3729-4208-955b-7b3a9b56809e)

**Comment by sylviiu** [comment]
Issue was definitely still there. I originally thought it was possibly an issue with network conditions (since it was hit or miss for me), but it was an issue with the download manager.

I'm building another nightly now, should release in less than 10 minutes from now -- let me know if this works! I feel confident the issue has been fixed this time.

(i did not mean to close the issue in the commit, i still need to learn the commit keywords)

**Comment by avatarDD** [comment]
> Issue was definitely still there. I originally thought it was possibly an issue with network conditions (since it was hit or miss for me), but it was an issue with the download manager.
> 
> [I'm building another nightly now](https://github.com/sylviiu/ezytdl/actions/runs/5914218670), should release in less than 10 minutes from now -- let me know if this works! I feel confident the issue has been fixed this time.
> 
> (i did not mean to close the issue in the commit, i still need to learn the commit keywords)

The problem is gone. In addition, the download began to be carried out in 4 streams. Excellent! :)

It remains only to add the function of downloading the entire discography of artist that not clicking on each album. And it will be just wonderful.

Thanks

**Comment by sylviiu** [comment]
I have yet to properly add that with Spotify, but I definitely can say that yt-dlp supports downloading entire channels / artists! If you find the artist on YouTube Music (or their YouTube channel) you should be able to download all of it!

I'm glad everything works well now! I'll go ahead and close the issue then.

I'll look into entire discography downloading with Spotify soon :)

**Comment by avatarDD** [comment]
It would also be nice to add the function of saving an audio track from *.mp4 without compression into *.m4a
![изображение](https://github.com/sylviiu/ezytdl/assets/11490349/5968c268-ac04-48db-941f-8bb1cbd4976e)

**Comment by sylviiu** [comment]
As much as I'd love to make that an official thing with the app, there's no way to actually check for a suitable file type for a specific audio codec through FFmpeg, and I don't think hard coding it is a very good solution to that.

*HOWEVER,* you can actually create your own preset in the app to specifically extract an audio stream and save as m4a!
*(`-vn` option had issues in `dev.154`, update to `dev.155` for that option to work :D)*

To extract the audio codec and save as an m4a from specific mp4 files (or an entire directory), you can do this in the Convert tab in app.

First, go to the settings page, scroll to the bottom, and enable "Show Advanced Options"
![image](https://github.com/sylviiu/ezytdl/assets/95180094/56e31573-995d-4367-aeb5-315e59594b96)

Next, head over to the Convert tab in app, and either select the files you'd like to convert or select an entire folder
![image](https://github.com/sylviiu/ezytdl/assets/95180094/f0bc6809-13b1-4933-88d8-d92019930733)

Click on "Custom Conversion," set `ext` to m4a, and `Additional Output Arguments` to `-vn -c:a copy` (as mentioned before), and click "Save as Preset." Set a fitting name and description that fits for you :)
![image](https://github.com/sylviiu/ezytdl/assets/95180094/c2a1eb5e-4e3e-4877-bb0a-96799016d560)

*(there is a bug in app that i have yet to get around to fixing; the preset will likely not show up until you open and close the settings page again -- this forcibly refreshes the config on the app side, you may need to do this)*

Click this button again for the new preset to show up (after the settings page if necessary)
![image](https://github.com/sylviiu/ezytdl/assets/95180094/559f08d8-dfae-4641-b826-f7147a370855)

And now you should be able to convert all of them to an m4a extracting the audio stream!
![image](https://github.com/sylviiu/ezytdl/assets/95180094/4b8b5ae7-bcae-4de3-acd2-17c3171dfe8d)

(destination directory for these files will not be the same as set in settings for downloaded media; they will be placed in the same directory as the source file)
